version: '3.8'

services:
  api:
    image: 'alta0815/assetsfirst-api:latest'
    expose:
      - "8080"
    env_file:
      - prod.env
    environment:
      - VIRTUAL_PORT=8080
    networks:
      - 'net'
  nginx:
    image: 'nginxproxy/nginx-proxy:latest'
    container_name: 'nginx-proxy'
    volumes:
      - 'html:/usr/share/nginx/html'
      - 'dhparam:/etc/nginx/dhparam'
      - 'vhost:/etc/nginx/vhost.d'
      - 'certs:/etc/nginx/certs'
      - 'conf:/etc/nginx/conf.d'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
    restart: 'always'
    networks:
      - 'net'
    ports:
      - '80:80'
      - '443:443'

  acme:
    image: 'nginxproxy/acme-companion:latest'
    container_name: 'nginx-proxy-acme-companion'
    depends_on:
      - 'nginx'
    volumes_from:
      - 'nginx'
    volumes:
      - 'acme:/etc/acme.sh'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    environment:
      NGINX_PROXY_CONTAINER: 'nginx-proxy'
      DEFAULT_EMAIL: 'help@assetsfirst.ru'
    restart: 'always'
    networks:
      - 'net'

volumes:
  html:
  dhparam:
  vhost:
  certs:
  conf:
  acme:

networks:
  net:
