spring:
  liquibase:
    enabled: 'true'
  jpa:
    hibernate:
      ddl-auto: validate
app:
  cookie-domain: assetsfirst.ru
  allowed-origins: https://assetsfirst.ru, https://api.assetsfirst.ru

management:
  httpexchanges:
    recording:
      enabled: false
