spring:
  datasource:
    hikari:
      connection-timeout: '40000'
      idle-timeout: '10000'
      maximum-pool-size: '20'
      minimum-idle: '5'
      max-lifetime: '30000'
  liquibase:
    enabled: 'true'
  jpa:
    hibernate:
      ddl-auto: validate
app:
  cookie-domain: assetsfirst.ru
  allowed-origins: https://assetsfirst.ru, https://api.assetsfirst.ru
