logging:
  level:
    org:
      springframework:
        security: DEBUG
        messaging: warn
        web:
          socket: warn
spring:
  datasource:
    url: jdbc:mysql://CAPITAL:CAPITAL@localhost:3306/investments?useSSL=false
  liquibase:
    enabled: 'false'
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: create
app:
  bootstrap:
    with:
      data: 'true'
