spring:
  datasource:
    hikari:
      idle-timeout: '10000'
      maximum-pool-size: '10'
      max-lifetime: '1000'
      connection-timeout: '20000'
      minimum-idle: '0'
  liquibase:
    enabled: 'true'
  jpa:
    hibernate:
      ddl-auto: validate
