spring:
  application:
    name: AssetsFirst
  jpa:
    properties:
      hibernate:
        types:
          print:
            banner: 'false'
        jdbc:
          time_zone: UTC
    open-in-view: false
  data:
    web:
      pageable:
        one-indexed-parameters: 'true'
  main:
    banner-mode: 'off'

app:
  allowed-origins: http://localhost:4200
  bootstrap:
    with:
      data: 'false'
  scheduler:
    realized-pnl:
      enabled: false
      cron: "0 */10 * * * ?"
  integration:
    free-currency:
      key: ${APP_INTEGRATION_FREE_CURRENCY_KEY:}

springdoc:
  swagger-ui:
    csrf:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
