spring:
  datasource:
    url: jdbc:mysql://CAPITAL:CAPITAL@localhost:3306/investments
  liquibase:
    enabled: 'true'
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: 'true'
        format_sql: true
