server:
  port: ${APP_PORT:8080}
spring:
  application:
    name: AssetsFirst
  jpa:
    properties:
      hibernate:
        types:
          print:
            banner: 'false'
        jdbc:
          time_zone: UTC
    open-in-view: false
  data:
    web:
      pageable:
        one-indexed-parameters: 'true'
  main:
    banner-mode: 'off'

app:
  allowed-origins: http://localhost:4200
  bootstrap:
    with:
      data: ${APP_BOOTSTRAP_WITH_DATA:false}
  scheduler:
    realized-pnl:
      enabled: false
      cron: "0 */10 * * * ?"
  integration:
    free-currency:
      key: ${APP_INTEGRATION_FREE_CURRENCY_KEY:}
  demo-data:
    username: demo

springdoc:
  swagger-ui:
    csrf:
      enabled: true
  default-produces-media-type: 'application/json'

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, httpexchanges
