spring:
  jpa:
    properties:
      hibernate:
        types:
          print:
            banner: 'false'
        jdbc:
          time_zone: UTC
    open-in-view: false
  data:
    web:
      pageable:
        one-indexed-parameters: 'true'
  main:
    banner-mode: 'off'

app:
  allowed-origins: http://localhost:4200
  bootstrap:
    with:
      data: 'false'

springdoc:
  swagger-ui:
    csrf:
      enabled: true
