name: Publish findata package

on:
  push:
    branches: [ "master" ]
    paths:
      - findata/**
  workflow_dispatch:
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./findata
    permissions:
      contents: write
      packages: write
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          always-auth: true
      - run: npm ci
      - run: git config --global user.name 'AssetsFirst'
      - run: git config --global user.email 'release@assetsfirst.ru'
      - run: |
          ver=$(npm version patch) \
          git add package.json package-lock.json
      - run: git commit -m '[RELEASE] $ver'
      - run: git push
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
