name: Pull Data

on:
  workflow_dispatch:
  schedule:
    - cron: "50 23 * * *"

jobs:
  pull-mcx-prices:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: read
    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          always-auth: true
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Moscow"
          timezoneMacos: "Europe/Moscow"
          timezoneWindows: "Russian Standard Time"
      - run: npm i @pods13/findata
      - run: npx -p @pods13/findata prices-ru

