name: Pull Price Data

on:
  workflow_dispatch:
  schedule:
    - cron: "28 1,9,10,12,15,17,19 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull-global-prices:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: findata
    permissions:
      contents: read
      packages: read
    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          always-auth: true
      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Europe/Moscow"
          timezoneMacos: "Europe/Moscow"
          timezoneWindows: "Russian Standard Time"
      - run: npm i @pods13/findata
      - name: pull new global prices
        timeout-minutes: 10
        run: npx -p @pods13/findata prices-global

  pull-mcx-prices:
    needs: pull-global-prices
    runs-on: self-hosted
    defaults:
      run:
        working-directory: findata
    permissions:
      contents: read
      packages: read
    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: powershell allow...
        shell: cmd
        run: powershell -Command "Set-ExecutionPolicy RemoteSigned -Scope CurrentUser"
      - name: check powershell version
        run: $host.Version
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          always-auth: true
      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Europe/Moscow"
          timezoneMacos: "Europe/Moscow"
          timezoneWindows: "Russian Standard Time"
      - run: npm i @pods13/findata
      - name: pull new ru prices
        timeout-minutes: 10
        run: npx -p @pods13/findata prices-ru

