name: Pull Price Data

on:
  workflow_dispatch:
  schedule:
    - cron: "28 1,9,10,12,15,17,19 * * *"

jobs:
  pull-global-prices:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: findata
    permissions:
      contents: read
      packages: read
    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          always-auth: true
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Europe/Moscow"
          timezoneMacos: "Europe/Moscow"
          timezoneWindows: "Russian Standard Time"
      - run: npm i @pods13/findata
      - name: pull new global prices
        timeout-minutes: 10
        run: npx -p @pods13/findata prices-global

  pull-mcx-prices:
    needs: pull-global-prices
    runs-on: self-hosted
    defaults:
      run:
        working-directory: findata
    permissions:
      contents: read
      packages: read
    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          always-auth: true
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Europe/Moscow"
          timezoneMacos: "Europe/Moscow"
          timezoneWindows: "Russian Standard Time"
      - run: npm i @pods13/findata
      - name: pull new ru prices
        timeout-minutes: 10
        run: npx -p @pods13/findata prices-ru

